import { describe, expect, it } from "vitest";

import { depositAmountFor, solicitarDepositoInputSchema } from "@dpm/shared";

import {
  generateRefCode,
  isValidRefCode,
  parseSolicitarDepositoInput,
} from "../src/tools/solicitar-deposito.js";
import {
  buildPaymentInstructions,
  sedeHasAutomaticGateway,
} from "../src/services/deposit-instructions.js";

describe("generateRefCode — DPM-<SEDE>-MMDD-XXXXXX format (Miguel feedback 2026-06-06: per-sede prefix)", () => {
  it("defaults to DPM-GT-... when no sede passed (backward compat for legacy callers)", () => {
    const code = generateRefCode();
    expect(code).toMatch(/^DPM-GT-\d{4}-[A-HJKMNPQRSTUVWXYZ23456789]{6}$/);
  });

  it("emits DPM-PP-... for Koh Phi Phi", () => {
    const code = generateRefCode("Koh Phi Phi");
    expect(code).toMatch(/^DPM-PP-\d{4}-[A-HJKMNPQRSTUVWXYZ23456789]{6}$/);
  });

  it("emits DPM-GT-... for Gili Trawangan", () => {
    const code = generateRefCode("Gili Trawangan");
    expect(code).toMatch(/^DPM-GT-\d{4}-[A-HJKMNPQRSTUVWXYZ23456789]{6}$/);
  });

  it("emits DPM-GA-... for Gili Air", () => {
    expect(generateRefCode("Gili Air")).toMatch(/^DPM-GA-/);
  });

  it("emits DPM-KT-... for Koh Tao", () => {
    expect(generateRefCode("Koh Tao")).toMatch(/^DPM-KT-/);
  });

  it("emits DPM-NP-... for Nusa Penida", () => {
    expect(generateRefCode("Nusa Penida")).toMatch(/^DPM-NP-/);
  });

  it("falls back to DPM-GT-... for unknown sede names (safety net)", () => {
    expect(generateRefCode("Unknown Sede Atlantis")).toMatch(/^DPM-GT-/);
  });

  it("uses sede-local timezone — Phi Phi UTC+7 produces correct MMDD slug", () => {
    // 2026-05-07 18:00 UTC === 2026-05-08 01:00 in Asia/Bangkok (Phi Phi).
    const code = generateRefCode("Koh Phi Phi", new Date("2026-05-07T18:00:00Z"));
    expect(code.startsWith("DPM-PP-0508-")).toBe(true);
  });

  it("uses sede-local timezone — Gili Trawangan UTC+8 produces correct MMDD slug", () => {
    // 2026-05-07 18:00 UTC === 2026-05-08 02:00 in Asia/Makassar (GT).
    const code = generateRefCode("Gili Trawangan", new Date("2026-05-07T18:00:00Z"));
    expect(code.startsWith("DPM-GT-0508-")).toBe(true);
  });

  it("avoids ambiguous characters (0/O, 1/I/L)", () => {
    for (let i = 0; i < 50; i++) {
      const code = generateRefCode("Koh Phi Phi");
      const suffix = code.slice(-6);
      expect(suffix).not.toMatch(/[0O1IL]/);
    }
  });

  it("produces unique codes across many invocations (collision probability negligible)", () => {
    const codes = new Set<string>();
    for (let i = 0; i < 200; i++) codes.add(generateRefCode("Koh Phi Phi"));
    expect(codes.size).toBe(200);
  });
});

describe("isValidRefCode", () => {
  it("accepts well-formed codes from any sede generated by the tool", () => {
    const sedes = ["Koh Phi Phi", "Gili Trawangan", "Gili Air", "Koh Tao", "Nusa Penida"];
    for (const sede of sedes) {
      for (let i = 0; i < 5; i++) {
        expect(isValidRefCode(generateRefCode(sede))).toBe(true);
      }
    }
  });

  it("accepts each of the 5 known sede prefixes explicitly", () => {
    expect(isValidRefCode("DPM-PP-0606-A7B3K2")).toBe(true);
    expect(isValidRefCode("DPM-GT-0512-A7B3K2")).toBe(true);
    expect(isValidRefCode("DPM-GA-0512-A7B3K2")).toBe(true);
    expect(isValidRefCode("DPM-KT-0512-A7B3K2")).toBe(true);
    expect(isValidRefCode("DPM-NP-1231-XYZK24")).toBe(true);
  });

  it("accepts any 2-letter sede prefix (forward-compat for new sedes)", () => {
    // Broadening the regex means adding a new sede to SEDE_REFCODE_PREFIXES
    // does NOT require updating the validator. The 2-letter shape is what
    // matters; the specific letters are a soft contract.
    expect(isValidRefCode("DPM-XX-0512-A7B3K2")).toBe(true);
    expect(isValidRefCode("DPM-ZZ-1231-AAAAA2")).toBe(true);
  });

  it("still accepts legacy DPM-XXXXXX (issued before 2026-05-07)", () => {
    expect(isValidRefCode("DPM-A7B3K2")).toBe(true);
  });

  it("rejects malformed strings", () => {
    expect(isValidRefCode("DPM-GT-0512-A7B3K")).toBe(false); // suffix too short
    expect(isValidRefCode("DPM-GT-051-A7B3K2")).toBe(false); // 3-digit MMDD
    expect(isValidRefCode("DPM-GT-05122-A7B3K2")).toBe(false); // 5-digit MMDD
    expect(isValidRefCode("dpm-gt-0512-a7b3k2")).toBe(false); // lowercase
    expect(isValidRefCode("DPM-GT-0512-O0I1L4")).toBe(false); // ambiguous chars
    expect(isValidRefCode("DPM-XXX-0512-A7B3K2")).toBe(false); // 3-letter sede prefix
    expect(isValidRefCode("DPM-X-0512-A7B3K2")).toBe(false); // 1-letter sede prefix
    expect(isValidRefCode("DPM-A7B3K")).toBe(false); // legacy too short
    expect(isValidRefCode("")).toBe(false);
  });
});

describe("parseSolicitarDepositoInput", () => {
  it("accepts a valid payload (EUR)", () => {
    const out = parseSolicitarDepositoInput({
      sede_id: "11111111-1111-1111-1111-111111111111",
      cliente_idioma: "es",
      moneda_cliente: "EUR",
      pax: 2,
    });
    expect(out.ok).toBe(true);
    if (out.ok) {
      expect(out.value.moneda_cliente).toBe("EUR");
      expect(out.value.pax).toBe(2);
    }
  });

  it("accepts AUD (added per owner spec) and accepts THB (added for Phi Phi 2026-06-07)", () => {
    expect(
      parseSolicitarDepositoInput({
        sede_id: "11111111-1111-1111-1111-111111111111",
        cliente_idioma: "en",
        moneda_cliente: "AUD",
        pax: 1,
      }).ok,
    ).toBe(true);
    // THB was rejected pre-2026-06-07 (Phi Phi wasn't live). Now accepted
    // for local Thai customers — Miguel confirmed 1,000 THB per person.
    expect(
      parseSolicitarDepositoInput({
        sede_id: "11111111-1111-1111-1111-111111111111",
        cliente_idioma: "en",
        moneda_cliente: "THB",
        pax: 1,
      }).ok,
    ).toBe(true);
  });

  it("rejects invalid currency", () => {
    const out = parseSolicitarDepositoInput({
      sede_id: "11111111-1111-1111-1111-111111111111",
      cliente_idioma: "es",
      moneda_cliente: "JPY",
      pax: 1,
    });
    expect(out.ok).toBe(false);
  });

  it("rejects non-uuid sede_id", () => {
    const out = parseSolicitarDepositoInput({
      sede_id: "not-a-uuid",
      cliente_idioma: "es",
      moneda_cliente: "EUR",
      pax: 1,
    });
    expect(out.ok).toBe(false);
  });

  it("rejects missing pax (2026-05-12 fraud-risk fix)", () => {
    const out = parseSolicitarDepositoInput({
      sede_id: "11111111-1111-1111-1111-111111111111",
      cliente_idioma: "es",
      moneda_cliente: "EUR",
    });
    expect(out.ok).toBe(false);
  });

  it("rejects pax = 0 or > 20", () => {
    const base = {
      sede_id: "11111111-1111-1111-1111-111111111111",
      cliente_idioma: "es" as const,
      moneda_cliente: "EUR" as const,
    };
    expect(parseSolicitarDepositoInput({ ...base, pax: 0 }).ok).toBe(false);
    expect(parseSolicitarDepositoInput({ ...base, pax: 21 }).ok).toBe(false);
    expect(parseSolicitarDepositoInput({ ...base, pax: 1.5 }).ok).toBe(false);
  });

  it("zod schema directly mirrors the parser result", () => {
    const ok = solicitarDepositoInputSchema.safeParse({
      sede_id: "11111111-1111-1111-1111-111111111111",
      cliente_idioma: "en",
      moneda_cliente: "USD",
      pax: 3,
    });
    expect(ok.success).toBe(true);
  });

  // Miguel rule 2026-06-06: multi-program ref-code support.
  it("accepts optional programas array (multi-program booking)", () => {
    const out = parseSolicitarDepositoInput({
      sede_id: "11111111-1111-1111-1111-111111111111",
      cliente_idioma: "es",
      moneda_cliente: "USD",
      pax: 3,
      programas: ["TryScuba", "Refresh", "AOW"],
    });
    expect(out.ok).toBe(true);
    if (out.ok) {
      expect(out.value.programas).toEqual(["TryScuba", "Refresh", "AOW"]);
    }
  });

  it("rejects empty programas array", () => {
    const out = parseSolicitarDepositoInput({
      sede_id: "11111111-1111-1111-1111-111111111111",
      cliente_idioma: "es",
      moneda_cliente: "USD",
      pax: 1,
      programas: [],
    });
    expect(out.ok).toBe(false);
  });

  it("rejects programas array longer than 10 (DOS guard)", () => {
    const out = parseSolicitarDepositoInput({
      sede_id: "11111111-1111-1111-1111-111111111111",
      cliente_idioma: "es",
      moneda_cliente: "USD",
      pax: 1,
      programas: Array.from({ length: 11 }, (_, i) => `prog${i}`),
    });
    expect(out.ok).toBe(false);
  });

  it("omitting programas is still valid (single-program legacy path)", () => {
    const out = parseSolicitarDepositoInput({
      sede_id: "11111111-1111-1111-1111-111111111111",
      cliente_idioma: "es",
      moneda_cliente: "USD",
      pax: 1,
    });
    expect(out.ok).toBe(true);
    if (out.ok) {
      expect(out.value.programas).toBeUndefined();
    }
  });
});

describe("depositAmountFor", () => {
  it("returns 40 for EUR / GBP / AUD / USD", () => {
    expect(depositAmountFor("EUR")).toBe(40);
    expect(depositAmountFor("GBP")).toBe(40);
    expect(depositAmountFor("AUD")).toBe(40);
    expect(depositAmountFor("USD")).toBe(40);
  });

  it("returns 700,000 for IDR (special case)", () => {
    expect(depositAmountFor("IDR")).toBe(700_000);
  });
});

describe("buildPaymentInstructions", () => {
  it("includes amount, currency, ref code in Spanish by default", () => {
    const txt = buildPaymentInstructions({
      sedeNombre: "Gili Trawangan",
      language: "es",
      currency: "EUR",
      refCode: "DPM-A7B3K2",
    });
    expect(txt).toContain("40 EUR");
    expect(txt).toContain("DPM-A7B3K2");
    expect(txt).toContain("BE93 9050 6891 4867"); // real EUR IBAN from KB-03
    expect(txt).toContain("comprobante");
  });

  it("renders English when language starts with en", () => {
    const txt = buildPaymentInstructions({
      sedeNombre: "Gili Trawangan",
      language: "en",
      currency: "USD",
      refCode: "DPM-AAAAAA",
    });
    expect(txt).toContain("40 USD");
    expect(txt).toContain("DPM-AAAAAA");
    expect(txt).toContain("Community Federal Savings Bank"); // real USD account
    expect(txt).toContain("payment confirmation PDF");
  });

  it("renders the real KB-03 GBP block with sort code", () => {
    const txt = buildPaymentInstructions({
      sedeNombre: "Gili Trawangan",
      language: "en",
      currency: "GBP",
      refCode: "DPM-XYZABC",
    });
    expect(txt).toContain("Sort code: 23-08-01");
    expect(txt).toContain("55834953");
  });

  it("renders the real KB-03 AUD block with BSB", () => {
    const txt = buildPaymentInstructions({
      sedeNombre: "Gili Trawangan",
      language: "en",
      currency: "AUD",
      refCode: "DPM-XYZABC",
    });
    expect(txt).toContain("BSB: 774-001");
    expect(txt).toContain("222625669");
  });

  it("formats IDR amount as 700,000 with thousand separators", () => {
    const txt = buildPaymentInstructions({
      sedeNombre: "Gili Trawangan",
      language: "es",
      currency: "IDR",
      refCode: "DPM-XYZABC",
    });
    expect(txt).toContain("700,000 IDR");
    expect(txt).toContain("Bank Mandiri");
    expect(txt).toContain("1610010570609");
  });

  it("does NOT mention PDF for IDR (Indonesian mobile banking accepts screenshots)", () => {
    // Owner spec INSTRUCCIONES_PAGO §1 table: "Comprobante en IDR
    // | Screenshot aceptado (banca móvil indonesia)".
    const txtEn = buildPaymentInstructions({
      sedeNombre: "Gili Trawangan",
      language: "en",
      currency: "IDR",
      refCode: "DPM-XYZABC",
    });
    expect(txtEn).not.toContain("PDF");
    expect(txtEn).toContain("payment confirmation");

    const txtEs = buildPaymentInstructions({
      sedeNombre: "Gili Trawangan",
      language: "es",
      currency: "IDR",
      refCode: "DPM-XYZABC",
    });
    expect(txtEs).not.toContain("PDF");
    expect(txtEs).toContain("comprobante");
  });

  it("renders with blank lines separating head / bank / reference / tail (WhatsApp readability)", () => {
    // Owner spec INSTRUCCIONES_PAGO §4: each section is its own paragraph
    // so the message reads cleanly in WhatsApp.
    const txt = buildPaymentInstructions({
      sedeNombre: "Gili Trawangan",
      language: "en",
      currency: "EUR",
      refCode: "DPM-A1B2C3",
    });
    // Head, then blank line, then "Beneficiary:" line.
    expect(txt).toMatch(/40 EUR 🙏\n\nBeneficiary:/);
    // Last bank line, blank line, then "Reference:".
    expect(txt).toMatch(/Wise, Brussels, Belgium\n\nReference: DPM-A1B2C3/);
    // Reference line, blank line, then tail.
    expect(txt).toMatch(/Reference: DPM-A1B2C3\n\nOnce sent/);
  });
});

describe("sedeHasAutomaticGateway", () => {
  it("reports no automatic gateway for any sede during pilot (Stripe deferred)", () => {
    expect(sedeHasAutomaticGateway("Koh Tao")).toBe(false);
    expect(sedeHasAutomaticGateway("Koh Phi Phi")).toBe(false);
    expect(sedeHasAutomaticGateway("Gili Trawangan")).toBe(false);
    expect(sedeHasAutomaticGateway("Gili Air")).toBe(false);
    expect(sedeHasAutomaticGateway("Nusa Penida")).toBe(false);
  });
});
