import { describe, expect, it } from "vitest";

import { depositAmountFor, solicitarDepositoInputSchema } from "@dpm/shared";

import {
  generateRefCode,
  isValidRefCode,
  parseSolicitarDepositoInput,
} from "../src/tools/solicitar-deposito.js";
import {
  buildPaymentInstructions,
  sedeHasAutomaticGateway,
} from "../src/services/deposit-instructions.js";

describe("generateRefCode", () => {
  it("starts with DPM- and contains 6 alphanumerics", () => {
    const code = generateRefCode();
    expect(code).toMatch(/^DPM-[A-HJKMNPQRSTUVWXYZ23456789]{6}$/);
  });

  it("avoids ambiguous characters (0/O, 1/I/L)", () => {
    for (let i = 0; i < 50; i++) {
      const code = generateRefCode();
      const body = code.slice(4);
      expect(body).not.toMatch(/[0O1IL]/);
    }
  });

  it("produces unique codes across many invocations (collision probability negligible)", () => {
    const codes = new Set<string>();
    for (let i = 0; i < 200; i++) codes.add(generateRefCode());
    expect(codes.size).toBe(200);
  });
});

describe("isValidRefCode", () => {
  it("accepts well-formed codes generated by the tool", () => {
    for (let i = 0; i < 20; i++) {
      expect(isValidRefCode(generateRefCode())).toBe(true);
    }
  });

  it("rejects malformed strings (legacy or hand-typed)", () => {
    expect(isValidRefCode("DPM-A7B3K2")).toBe(true);
    expect(isValidRefCode("DPM-A7B3K")).toBe(false); // too short
    expect(isValidRefCode("DPM-A7B3K20")).toBe(false); // too long
    expect(isValidRefCode("dpm-a7b3k2")).toBe(false); // lowercase
    expect(isValidRefCode("DPM-O0I1L4")).toBe(false); // ambiguous chars
    expect(isValidRefCode("XYZ-A7B3K2")).toBe(false); // wrong prefix
    expect(isValidRefCode("")).toBe(false);
  });
});

describe("parseSolicitarDepositoInput", () => {
  it("accepts a valid payload (EUR)", () => {
    const out = parseSolicitarDepositoInput({
      sede_id: "11111111-1111-1111-1111-111111111111",
      cliente_idioma: "es",
      moneda_cliente: "EUR",
    });
    expect(out.ok).toBe(true);
    if (out.ok) {
      expect(out.value.moneda_cliente).toBe("EUR");
    }
  });

  it("accepts AUD (added per owner spec) and rejects THB (removed)", () => {
    expect(
      parseSolicitarDepositoInput({
        sede_id: "11111111-1111-1111-1111-111111111111",
        cliente_idioma: "en",
        moneda_cliente: "AUD",
      }).ok,
    ).toBe(true);
    expect(
      parseSolicitarDepositoInput({
        sede_id: "11111111-1111-1111-1111-111111111111",
        cliente_idioma: "en",
        moneda_cliente: "THB",
      }).ok,
    ).toBe(false);
  });

  it("rejects invalid currency", () => {
    const out = parseSolicitarDepositoInput({
      sede_id: "11111111-1111-1111-1111-111111111111",
      cliente_idioma: "es",
      moneda_cliente: "JPY",
    });
    expect(out.ok).toBe(false);
  });

  it("rejects non-uuid sede_id", () => {
    const out = parseSolicitarDepositoInput({
      sede_id: "not-a-uuid",
      cliente_idioma: "es",
      moneda_cliente: "EUR",
    });
    expect(out.ok).toBe(false);
  });

  it("zod schema directly mirrors the parser result", () => {
    const ok = solicitarDepositoInputSchema.safeParse({
      sede_id: "11111111-1111-1111-1111-111111111111",
      cliente_idioma: "en",
      moneda_cliente: "USD",
    });
    expect(ok.success).toBe(true);
  });
});

describe("depositAmountFor", () => {
  it("returns 40 for EUR / GBP / AUD / USD", () => {
    expect(depositAmountFor("EUR")).toBe(40);
    expect(depositAmountFor("GBP")).toBe(40);
    expect(depositAmountFor("AUD")).toBe(40);
    expect(depositAmountFor("USD")).toBe(40);
  });

  it("returns 700,000 for IDR (special case)", () => {
    expect(depositAmountFor("IDR")).toBe(700_000);
  });
});

describe("buildPaymentInstructions", () => {
  it("includes amount, currency, ref code in Spanish by default", () => {
    const txt = buildPaymentInstructions({
      sedeNombre: "Gili Trawangan",
      language: "es",
      currency: "EUR",
      refCode: "DPM-A7B3K2",
    });
    expect(txt).toContain("40 EUR");
    expect(txt).toContain("DPM-A7B3K2");
    expect(txt).toContain("BE93 9050 6891 4867"); // real EUR IBAN from KB-03
    expect(txt).toContain("comprobante");
  });

  it("renders English when language starts with en", () => {
    const txt = buildPaymentInstructions({
      sedeNombre: "Gili Trawangan",
      language: "en",
      currency: "USD",
      refCode: "DPM-AAAAAA",
    });
    expect(txt).toContain("40 USD");
    expect(txt).toContain("DPM-AAAAAA");
    expect(txt).toContain("Community Federal Savings Bank"); // real USD account
    expect(txt).toContain("payment confirmation PDF");
  });

  it("renders the real KB-03 GBP block with sort code", () => {
    const txt = buildPaymentInstructions({
      sedeNombre: "Gili Trawangan",
      language: "en",
      currency: "GBP",
      refCode: "DPM-XYZABC",
    });
    expect(txt).toContain("Sort code: 23-08-01");
    expect(txt).toContain("55834953");
  });

  it("renders the real KB-03 AUD block with BSB", () => {
    const txt = buildPaymentInstructions({
      sedeNombre: "Gili Trawangan",
      language: "en",
      currency: "AUD",
      refCode: "DPM-XYZABC",
    });
    expect(txt).toContain("BSB: 774-001");
    expect(txt).toContain("222625669");
  });

  it("formats IDR amount as 700,000 with thousand separators", () => {
    const txt = buildPaymentInstructions({
      sedeNombre: "Gili Trawangan",
      language: "es",
      currency: "IDR",
      refCode: "DPM-XYZABC",
    });
    expect(txt).toContain("700,000 IDR");
    expect(txt).toContain("Bank Mandiri");
    expect(txt).toContain("1610010570609");
  });

  it("does NOT mention PDF for IDR (Indonesian mobile banking accepts screenshots)", () => {
    // Owner spec INSTRUCCIONES_PAGO §1 table: "Comprobante en IDR
    // | Screenshot aceptado (banca móvil indonesia)".
    const txtEn = buildPaymentInstructions({
      sedeNombre: "Gili Trawangan",
      language: "en",
      currency: "IDR",
      refCode: "DPM-XYZABC",
    });
    expect(txtEn).not.toContain("PDF");
    expect(txtEn).toContain("payment confirmation");

    const txtEs = buildPaymentInstructions({
      sedeNombre: "Gili Trawangan",
      language: "es",
      currency: "IDR",
      refCode: "DPM-XYZABC",
    });
    expect(txtEs).not.toContain("PDF");
    expect(txtEs).toContain("comprobante");
  });

  it("renders with blank lines separating head / bank / reference / tail (WhatsApp readability)", () => {
    // Owner spec INSTRUCCIONES_PAGO §4: each section is its own paragraph
    // so the message reads cleanly in WhatsApp.
    const txt = buildPaymentInstructions({
      sedeNombre: "Gili Trawangan",
      language: "en",
      currency: "EUR",
      refCode: "DPM-A1B2C3",
    });
    // Head, then blank line, then "Beneficiary:" line.
    expect(txt).toMatch(/40 EUR 🙏\n\nBeneficiary:/);
    // Last bank line, blank line, then "Reference:".
    expect(txt).toMatch(/Wise, Brussels, Belgium\n\nReference: DPM-A1B2C3/);
    // Reference line, blank line, then tail.
    expect(txt).toMatch(/Reference: DPM-A1B2C3\n\nOnce sent/);
  });
});

describe("sedeHasAutomaticGateway", () => {
  it("reports no automatic gateway for any sede during pilot (Stripe deferred)", () => {
    expect(sedeHasAutomaticGateway("Koh Tao")).toBe(false);
    expect(sedeHasAutomaticGateway("Koh Phi Phi")).toBe(false);
    expect(sedeHasAutomaticGateway("Gili Trawangan")).toBe(false);
    expect(sedeHasAutomaticGateway("Gili Air")).toBe(false);
    expect(sedeHasAutomaticGateway("Nusa Penida")).toBe(false);
  });
});
